### ISSUE TITLE
Compatibility with multiprocess

### ISSUE THREAD

**Issue by JimboJoe** [wallabag/firefox-ext-v2#34]
Could you please make this addon compatible with the new Firefox multiprocess feature?
For more information: https://wiki.mozilla.org/Electrolysis

Thanks and keep up the good work!

**Comment by zertrin** [comment]
I'm using Firefox 52.0a2 (2016-11-27) (32-bit) developer edition on Win 7 64 bit and been using wallabag's firefox extension without any problem since I activated multiprocess months ago.

I reported it as compatible through the Add-on Compatibility Reporter.

I guess, from what I've read, that the extension's developer has to set some variable to True to really mark the extension as compatible (`multiProcessCompatible` seems to be it) or migrate to WebExtensions.

I guess in the short term, the first option is what @JimboJoe is asking for, isn't it?

**Comment by Simounet** [comment]
Hi,
I will look into that in the next few days. The first option seems to be enough. For the future, we are thinking about switching to a web extension.

**Comment by JimboJoe** [comment]
@zertrin Thanks for testing, I was assuming that if Firefox was stating that it was incompatible with multiprocess, so it was :-)
So there seems to only be the need to set the mutiProcessCompatible flag to true.

**Comment by Simounet** [comment]
I tested it tonight and everything looks fine.
PR #35 is on the road folks. 🚀

**Comment by lapineige** [comment]
That's great news, thanks for this update ! :)

**Comment by ThibaudDauce** [comment]
The new version is out :-)
